# import os
import pickle
import pandas as pd
import numpy as np
import streamlit as st
import requests
# import ast
# from nltk.stem.porter import PorterStemmer
# from sklearn.feature_extraction.text import CountVectorizer
# from sklearn.metrics.pairwise import cosine_similarity

API_KEY = "e749164ed1aa86a57548ab5e975a1251"

@st.cache_data  
def load_data():
    """Load pre-computed pickle files generated by regenerate_pickles.py"""
    try:
        with open('movies.pkl', 'rb') as f:
            moviesdf = pickle.load(f)
        with open('similarity.pkl', 'rb') as f:
            similarity = pickle.load(f)
        with open('movies_info.pkl', 'rb') as f:
            movies_info = pickle.load(f)
        return moviesdf, similarity, movies_info
    except FileNotFoundError:
        st.error("Pickle files not found! Run regenerate_pickles.py first.")
        st.stop()


def fetch_poster(movie_id, api_key=API_KEY):
    """
    Fetch movie poster image from TMDB API using movie_id and api_key.
    
    This function calls the TMDB API to retrieve movie details and extracts
    the poster image URL. Uses the same API integration as regenerate_pickles.py.
    
    Args:
        movie_id: The TMDB movie ID
        api_key: The TMDB API key (uses default if not provided)
        
    Returns:
        Full URL path to the poster image, or placeholder if unavailable
    """
    url = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={api_key}&language=en-US"
    try:
        response = requests.get(url)
        data = response.json()
        if 'poster_path' in data and data['poster_path']:
            full_path = "https://image.tmdb.org/t/p/w500/" + data['poster_path']
            return full_path
        else:
            return "https://via.placeholder.com/500x750?text=No+Image"
    except Exception as e:
        st.warning(f"Could not fetch poster for movie ID {movie_id}")
        return "https://via.placeholder.com/500x750?text=No+Image"

def recommend(movie):
    """
    Get top 10 movie recommendations based on 5000 features using cosine similarity.
    
    This function implements the same recommendation logic as regenerate_pickles.py:
    - Uses pre-computed similarity matrix based on 5000 features
    - Applies CountVectorizer with stop_words='english' (from regenerate_pickles.py)
    - Sorts by similarity score and returns top 10 recommendations
    
    Args:
        movie: Movie title to get recommendations for
        
    Returns:
        Two lists: recommended movie titles with years and their poster URLs
    """
    try:
        movie_index = moviesdf[moviesdf['title'] == movie].index[0]
        distances = similarity[movie_index]
        # Sort by similarity score in descending order, get top 10 (excluding the movie itself at index 0)
        movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:11]
    
        recommended_movies = []
        recommended_movie_posters = []
    
        for i in movies_list:
            idx = i[0]
            movie_id = moviesdf.iloc[idx]['movie_id']
            title = moviesdf.iloc[idx]['title']
            year = movies_info.iloc[idx]['year']
        
            recommended_movies.append(f"{title} ({year})")
            # Fetch poster image from TMDB API
            recommended_movie_posters.append(fetch_poster(movie_id))
    
        return recommended_movies, recommended_movie_posters
    except IndexError:
        st.error("Movie not found in database!")
        return [], []

st.title('Movie Recommender System')
moviesdf, similarity, movies_info = load_data()


#Movie selection
selected_movie_name = st.selectbox(
    'Type or select a movie you like',
    moviesdf['title'].values
)

if st.button('Show Recommendations'):
    with st.spinner('Getting recommendations...'):
        names, posters = recommend(selected_movie_name)
    if names:
        st.subheader(f"Top 10 Recommendations for '{selected_movie_name}'")
    
        # Display recommendations in a grid layout (5 movies per row)
        cols = st.columns(5)
        for idx, (name, poster) in enumerate(zip(names, posters)):
            col = cols[idx % 5]
            with col:
                st.image(poster, width=400)
                st.caption(name)